---
  - name: "make sure to use project {{ THOTH_MIDDLETIER_NAMESPACE }}"
    command: "oc project {{ THOTH_MIDDLETIER_NAMESPACE }}"
    register: project_exists
    ignore_errors: true

  - name: importing CentOS7 Python3.6 S2I container images from CentOS
    command: "oc import-image registry.centos.org/centos/python-36-centos7 --confirm"
    ignore_errors: true
    register: cent_os_registry

  - name: importing CentOS7 Python3.6 S2I container images from Docker
    command: "oc import-image docker.io/centos/python-36-centos7 --confirm"
    when: cent_os_registry is failed

  - name: create required secrets
    command: oc new-app --template="{{ THOTH_INFRA_NAMESPACE  }}/thoth-core-secret" \
        -p THOTH_SECRET="{{ THOTH_SECRET }}" \
        -p THOTH_CEPH_KEY_ID="{{ THOTH_CEPH_KEY_ID }}" \
        -p THOTH_CEPH_SECRET_KEY="{{ THOTH_CEPH_SECRET_KEY }}"
    ignore_errors: true

  - name: create required configmaps
    command: oc new-app --template="{{ THOTH_INFRA_NAMESPACE  }}/thoth-core-configmap" \
        -p THOTH_DEPLOYMENT_NAME="{{ THOTH_DEPLOYMENT_NAME }}" \
        -p THOTH_FRONTEND_NAMESPACE="{{ THOTH_FRONTEND_NAMESPACE }}" \
        -p THOTH_MIDDLEEND_NAMESPACE="{{ THOTH_MIDDLETIER_NAMESPACE }}" \
        -p THOTH_BACKEND_NAMESPACE="{{ THOTH_BACKEND_NAMESPACE }}" \
        -p THOTH_CEPH_HOST="{{ THOTH_CEPH_HOST }}" \
        -p THOTH_CEPH_BUCKET="{{ THOTH_CEPH_BUCKET }}"
    ignore_errors: true

  - name: deploy Thoth Result API
    command: oc new-app --template="{{ THOTH_INFRA_NAMESPACE  }}/result-api-deployment"

  - name: deploy Thoth Result API BuildConfig
    command: oc new-app --template="{{ THOTH_INFRA_NAMESPACE  }}/result-api-buildconfig"

  - name: deploy JanusGraph Database
    command: "oc new-app --template={{ THOTH_INFRA_NAMESPACE }}/janusgraph"
    ignore_errors: true
