organization: thoth-station
repositories:
  - core
  - user-api
  - common
  - storages
  - package-releases-job
  - graph-refresh-job
  - result-api
  - solver
  - graph-sync-job
  - cleanup-job
  - package-extract
  - adviser
  - analyzer
  - build-analysers
  - dependency-monkey
  - notebooks
  - jupyter-notebook
  - lab
  - naming-service
defaultLabels:
  - name: 'approved'
    color: '00cc00'
  - name: 'do-not-merge'
    color: 'cc0000'
  - name: 'work-in-progress'
    color: 'cc0000'
  - name: 'needs-rebase'
    color: 'cc0000'