---
  - name: login to OpenShift using provided token
    command: "oc login --insecure-skip-tls-verify=true --token {{ token }} {{ openshift_master_url }}"
    changed_when: False
    
  - name: "create Thoth Tiers"
    command: "oc new-project {{ item }}"
    ignore_errors: true
    with_items:
      - "{{ THOTH_BACKEND_NAMESPACE  }}"
      - "{{ THOTH_MIDDLETIER_NAMESPACE }}"
      - "{{ THOTH_FRONTEND_NAMESPACE }}"
      - "{{ THOTH_INFRA_NAMESPACE }}"

  - name: "make sure to use project {{ THOTH_INFRA_NAMESPACE }}"
    command: "oc project {{ THOTH_INFRA_NAMESPACE }}"
    register: project_exists
    ignore_errors: true

  - name: create Thoth Core template
    command: oc create --namespace "{{ THOTH_INFRA_NAMESPACE  }}" --filename ../openshift/template.yaml

  - name: create Thoth Core secrets template
    command: oc create --namespace "{{ THOTH_INFRA_NAMESPACE  }}" --filename ../openshift/secret-template.yaml

  - name: create Thoth Core configmap template
    command: oc create --namespace "{{ THOTH_INFRA_NAMESPACE  }}" --filename ../openshift/configmap-template.yaml
 
  - name: create JanusGraph Database Template
    command: oc create --namespace "{{ THOTH_INFRA_NAMESPACE }}" \
        --filename https://raw.githubusercontent.com/goern/janusgraph-openshift/master/template.yaml

  - name: create Thoth Core Deployment templates
    command: "oc create --namespace {{ THOTH_INFRA_NAMESPACE }} --filename {{ item }}"
    with_items:
      - https://raw.githubusercontent.com/thoth-station/user-api/master/openshift/deployment-template.yaml
      - https://raw.githubusercontent.com/thoth-station/result-api/master/openshift/deployment-template.yaml

  - name: create Thoth Core CronJob templates
    command: oc create --namespace "{{ THOTH_INFRA_NAMESPACE  }}" --filename "{{ item }}"
    with_items:
      - https://raw.githubusercontent.com/thoth-station/package-releases-job/master/openshift/cronJob-template.yaml
      - https://raw.githubusercontent.com/thoth-station/graph-refresh-job/master/openshift/cronJob-template.yaml
      - https://raw.githubusercontent.com/thoth-station/cleanup-job/master/openshift/cronJob-template.yaml
      - https://raw.githubusercontent.com/thoth-station/graph-sync-job/master/openshift/cronJob-template.yaml
      - https://raw.githubusercontent.com/thoth-station/cve-update-job/master/openshift/cronJob-template.yaml

  - name: create Thoth Core BuildConfig templates
    command: oc create --namespace "{{ THOTH_INFRA_NAMESPACE  }}" --filename "{{ item }}" 
    with_items:
      - https://raw.githubusercontent.com/thoth-station/user-api/master/openshift/buildConfig-template.yaml
      - https://raw.githubusercontent.com/thoth-station/result-api/master/openshift/buildConfig-template.yaml
      - https://raw.githubusercontent.com/thoth-station/package-releases-job/master/openshift/buildConfig-template.yaml
      - https://raw.githubusercontent.com/thoth-station/graph-refresh-job/master/openshift/buildConfig-template.yaml
      - https://raw.githubusercontent.com/thoth-station/cleanup-job/master/openshift/buildConfig-template.yaml
      - https://raw.githubusercontent.com/thoth-station/graph-sync-job/master/openshift/buildConfig-template.yaml
      - https://raw.githubusercontent.com/thoth-station/package-extract/master/openshift/buildConfig-template.yaml
      - https://raw.githubusercontent.com/thoth-station/adviser/master/openshift/buildConfig-template.yaml
      - https://raw.githubusercontent.com/thoth-station/solver/master/openshift/buildConfig-template.yaml
      - https://raw.githubusercontent.com/thoth-station/cve-update-job/master/openshift/buildConfig-template.yaml

  - name: create Thoth Core ImageStream templates
    command: oc create --namespace "{{ THOTH_INFRA_NAMESPACE  }}" --filename "{{ item }}"
    with_items:
      - https://raw.githubusercontent.com/thoth-station/package-releases-job/master/openshift/imageStream-template.yaml
      - https://raw.githubusercontent.com/thoth-station/graph-refresh-job/master/openshift/imageStream-template.yaml
      - https://raw.githubusercontent.com/thoth-station/cleanup-job/master/openshift/imageStream-template.yaml
      - https://raw.githubusercontent.com/thoth-station/graph-sync-job/master/openshift/imageStream-template.yaml
      - https://raw.githubusercontent.com/thoth-station/adviser/master/openshift/imageStream-template.yaml
      - https://raw.githubusercontent.com/thoth-station/package-extract/master/openshift/imageStream-template.yaml
      - https://raw.githubusercontent.com/thoth-station/solver/master/openshift/imageStream-template.yaml
      - https://raw.githubusercontent.com/thoth-station/cve-update-job/master/openshift/imageStream-template.yaml
