---
  - name: "make sure to use project {{ THOTH_FRONTEND_NAMESPACE }}"
    command: "oc project {{ THOTH_FRONTEND_NAMESPACE }}"
    register: project_exists
    ignore_errors: true

  - name: importing CentOS7 Python3.6 S2I container images from CentOS
    command: "oc import-image registry.centos.org/centos/python-36-centos7 --namespace {{ THOTH_FRONTEND_NAMESPACE }} --confirm"
    ignore_errors: true
    register: cent_os_registry

  - name: importing CentOS7 Python3.6 S2I container images from Docker
    command: "oc import-image docker.io/centos/python-36-centos7 --namespace {{ THOTH_FRONTEND_NAMESPACE }} --confirm"
    when: cent_os_registry is failed

  - name: create required secrets
    command: oc new-app --namespace {{ THOTH_FRONTEND_NAMESPACE }} --template="{{ THOTH_INFRA_NAMESPACE  }}/thoth-core-secret" \
        -p THOTH_SECRET="{{ THOTH_SECRET }}" \
        -p THOTH_CEPH_KEY_ID="{{ THOTH_CEPH_KEY_ID }}" \
        -p THOTH_CEPH_SECRET_KEY="{{ THOTH_CEPH_SECRET_KEY }}"
    ignore_errors: true

  - name: create required configmaps
    command: oc new-app --namespace {{ THOTH_FRONTEND_NAMESPACE }} --template="{{ THOTH_INFRA_NAMESPACE  }}/thoth-core-configmap" \
        -p THOTH_DEPLOYMENT_NAME="{{ THOTH_DEPLOYMENT_NAME }}" \
        -p THOTH_FRONTEND_NAMESPACE="{{ THOTH_FRONTEND_NAMESPACE }}" \
        -p THOTH_MIDDLEEND_NAMESPACE="{{ THOTH_MIDDLETIER_NAMESPACE }}" \
        -p THOTH_BACKEND_NAMESPACE="{{ THOTH_BACKEND_NAMESPACE }}" \
        -p THOTH_CEPH_HOST="{{ THOTH_CEPH_HOST }}" \
        -p THOTH_CEPH_BUCKET="{{ THOTH_CEPH_BUCKET }}"
    ignore_errors: true

  - name: deploy Thoth Core
    command: oc new-app --template="{{ THOTH_INFRA_NAMESPACE  }}/thoth-core" \
        -p THOTH_FRONTEND_NAMESPACE="{{ THOTH_FRONTEND_NAMESPACE }}" \
        -p THOTH_MIDDLEEND_NAMESPACE="{{ THOTH_MIDDLETIER_NAMESPACE }}" \
        -p THOTH_BACKEND_NAMESPACE="{{ THOTH_BACKEND_NAMESPACE }}"
    ignore_errors: true

  - name: deploy Thoth User API
    command: oc new-app --template="{{ THOTH_INFRA_NAMESPACE  }}/thoth-user-api-deployment" \
        -p THOTH_FRONTEND_NAMESPACE="{{ THOTH_FRONTEND_NAMESPACE }}"

  - name: deploy Thoth User API BuildConfig
    command: oc new-app --template="{{ THOTH_INFRA_NAMESPACE  }}/thoth-user-api-buildconfig"
    ignore_errors: true

  - name: create Thoth Package Releases CronJob
    command: oc new-app --template="{{ THOTH_INFRA_NAMESPACE  }}/package-releases-cronjob"

  - name: create Thoth Package Releases BuildConfig
    command: oc new-app --template="{{ THOTH_INFRA_NAMESPACE  }}/package-releases-buildconfig"

  - name: create Thoth Package Releases ImageStream
    command: oc new-app --template="{{ THOTH_INFRA_NAMESPACE  }}/package-releases-imagestream"

  - name: create Thoth Graph Sync CronJob
    command: oc new-app --template="{{ THOTH_INFRA_NAMESPACE  }}/graph-sync-cronjob"

  - name: create Thoth Graph Sync BuildConfig
    command: oc new-app --template="{{ THOTH_INFRA_NAMESPACE  }}/graph-sync-buildconfig"

  - name: create Thoth Graph Sync ImageStream
    command: oc new-app --template="{{ THOTH_INFRA_NAMESPACE  }}/graph-sync-imagestream"

  - name: create Thoth Graph Refresh CronJob
    command: oc new-app --template="{{ THOTH_INFRA_NAMESPACE  }}/graph-refresh-cronjob"

  - name: create Thoth Graph Refresh BuildConfig
    command: oc new-app --template="{{ THOTH_INFRA_NAMESPACE  }}/graph-refresh-buildconfig"

  - name: create Thoth Graph Refresh ImageStream
    command: oc new-app --template="{{ THOTH_INFRA_NAMESPACE  }}/graph-refresh-imagestream"

  - name: create Thoth Cleanup CronJob
    command: oc new-app --template="{{ THOTH_INFRA_NAMESPACE  }}/cleanup-cronjob"

  - name: create Thoth Cleanup BuildConfig
    command: oc new-app --template="{{ THOTH_INFRA_NAMESPACE  }}/cleanup-buildconfig"

  - name: create Thoth Cleanup ImageStream
    command: oc new-app --template="{{ THOTH_INFRA_NAMESPACE  }}/cleanup-imagestream"
