---
  - name: "make sure to use project {{ THOTH_FRONTEND_NAMESPACE }}"
    command: "oc project {{ THOTH_FRONTEND_NAMESPACE }}"
    register: project_exists
    ignore_errors: true
    changed_when: False

  - name: create required secrets
    command: oc new-app --namespace {{ THOTH_FRONTEND_NAMESPACE }} --template="{{ THOTH_INFRA_NAMESPACE  }}/thoth-core-secret" \
        -p THOTH_APP_SECRET_KEY="{{ THOTH_APP_SECRET_KEY }}" \
        -p THOTH_SECRET="{{ THOTH_SECRET }}" \
        -p THOTH_CEPH_KEY_ID="{{ THOTH_CEPH_KEY_ID }}" \
        -p THOTH_CEPH_SECRET_KEY="{{ THOTH_CEPH_SECRET_KEY }}"
    ignore_errors: true

  - name: create required configmaps
    command: oc new-app --namespace {{ THOTH_FRONTEND_NAMESPACE }} --template="{{ THOTH_INFRA_NAMESPACE  }}/thoth-core-configmap" \
        -p THOTH_DEPLOYMENT_NAME="{{ THOTH_DEPLOYMENT_NAME }}" \
        -p THOTH_FRONTEND_NAMESPACE="{{ THOTH_FRONTEND_NAMESPACE }}" \
        -p THOTH_MIDDLETIER_NAMESPACE="{{ THOTH_MIDDLETIER_NAMESPACE }}" \
        -p THOTH_BACKEND_NAMESPACE="{{ THOTH_BACKEND_NAMESPACE }}" \
        -p THOTH_INFRA_NAMESPACE="{{ THOTH_INFRA_NAMESPACE }}" \
        -p THOTH_S3_ENDPOINT_URL="{{ THOTH_S3_ENDPOINT_URL  }}" \
        -p THOTH_CEPH_BUCKET="{{ THOTH_CEPH_BUCKET }}" \
        -p PROMETHEUS_PUSHGATEWAY_HOST="{{ PROMETHEUS_PUSHGATEWAY_HOST }}" \
        -p PROMETHEUS_PUSHGATEWAY_PORT="{{ PROMETHEUS_PUSHGATEWAY_PORT }}"
    ignore_errors: true

  - name: deploy Thoth Core
    command: oc new-app --template="{{ THOTH_INFRA_NAMESPACE  }}/thoth-core" \
        -p THOTH_FRONTEND_NAMESPACE="{{ THOTH_FRONTEND_NAMESPACE }}" \
        -p THOTH_MIDDLETIER_NAMESPACE="{{ THOTH_MIDDLETIER_NAMESPACE }}" \
        -p THOTH_BACKEND_NAMESPACE="{{ THOTH_BACKEND_NAMESPACE }}"
    ignore_errors: true

  - name: deploy Thoth User API
    command: oc new-app --template="{{ THOTH_INFRA_NAMESPACE  }}/user-api-deployment" \
        -p THOTH_FRONTEND_NAMESPACE="{{ THOTH_FRONTEND_NAMESPACE }}"

  - name: create Thoth Package Releases CronJob
    command: oc new-app --template="{{ THOTH_INFRA_NAMESPACE  }}/package-releases-cronjob" \
        -p THOTH_SUSPEND_CRONJOB="{{ THOTH_SUSPEND_CRONJOBS }}"

  - name: create Thoth Package Releases ImageStream
    command: oc new-app --template="{{ THOTH_INFRA_NAMESPACE  }}/package-releases-imagestream"

  - name: create Thoth Graph Sync CronJob
    command: oc new-app --template="{{ THOTH_INFRA_NAMESPACE  }}/graph-sync-cronjob" \
        -p THOTH_SUSPEND_CRONJOB="{{ THOTH_SUSPEND_CRONJOBS }}"

  - name: create Thoth Graph Sync ImageStream
    command: oc new-app --template="{{ THOTH_INFRA_NAMESPACE  }}/graph-sync-imagestream"

  - name: create Thoth Graph Refresh CronJob
    command: oc new-app --template="{{ THOTH_INFRA_NAMESPACE  }}/graph-refresh-cronjob" \
        -p THOTH_SUSPEND_CRONJOB="{{ THOTH_SUSPEND_CRONJOBS }}"

  - name: create Thoth Graph Refresh ImageStream
    command: oc new-app --template="{{ THOTH_INFRA_NAMESPACE  }}/graph-refresh-imagestream"

  - name: create Thoth Cleanup CronJob
    command: oc new-app --template="{{ THOTH_INFRA_NAMESPACE  }}/cleanup-cronjob" \
        -p THOTH_SUSPEND_CRONJOB="{{ THOTH_SUSPEND_CRONJOBS }}"

  - name: create Thoth Cleanup ImageStream
    command: oc new-app --template="{{ THOTH_INFRA_NAMESPACE  }}/cleanup-imagestream"
