apiVersion: v1
kind: Template
metadata:
  name: thoth-core-configmap
  annotations:
    description: >
      Thoth: All the configmaps required to deploy Thoth Core Analyzer and Results API
    openshift.io/display-name: Thoth Core Configmap
    version: 0.6.0
    tags: thoth,ai-stacks,aistacks
    template.openshift.io/documentation-url: https://github.com/Thoth-Station/
    template.openshift.io/long-description: >
      This template defines resources needed to deploy Thoth Core Services to OpenShift.
    template.openshift.io/provider-display-name: Red Hat, Inc.
  labels:
    app: thoth
    template: thoth-core-configmap
    component: configmap

objects:
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: thoth
      labels:
        app: thoth
        component: configmap
    data:
      frontend-namespace: ${THOTH_FRONTEND_NAMESPACE}
      middletier-namespace: ${THOTH_MIDDLETIER_NAMESPACE}
      middletier-pod-cpu-limit: "0.5"
      middletier-pod-memory-limit: "0.5Gi"
      backend-namespace: ${THOTH_BACKEND_NAMESPACE}
      infra-namespace: ${THOTH_INFRA_NAMESPACE}
      storage-bucket-name: ${THOTH_DEPLOYMENT_NAME}
      ceph-bucket-name: ${THOTH_CEPH_BUCKET}
      ceph-bucket-prefix: ${THOTH_CEPH_BUCKET_PREFIX}
      ceph-host: ${THOTH_S3_ENDPOINT_URL}
      ceph-results-path: /results
      analyzer-cleanup-time: ${THOTH_ANALYZER_CLEANUP_TIME}
      sync-observations: ${THOTH_SYNC_OBSERVATIONS}
      package-releases-only-if-package-seen: ${THOTH_PACKAGE_RELEASES_ONLY_IF_PACKAGE_SEEN}
      rsyslog-host: ${RSYSLOG_HOST}
      rsyslog-port: ${RSYSLOG_PORT}
      amun-api-url: ${AMUN_API_URL}
      isis-api-url: ${ISIS_API_URL}
      metrics-pushgateway-url: ${PROMETHEUS_PUSHGATEWAY_HOST}:${PROMETHEUS_PUSHGATEWAY_PORT}
      sentry-environment: ${SENTRY_ENVIRONMENT}

parameters:
  - description: Name of the Thoth Frontend Namespace
    displayName: Thoth Frontend Namespace
    required: true
    name: THOTH_FRONTEND_NAMESPACE

  - description: Name of the Thoth Middle Tier Namespace
    displayName: Thoth Middle Tier Namespace
    required: true
    name: THOTH_MIDDLETIER_NAMESPACE

  - description: Name of the Thoth Backend Namespace
    displayName: Thoth Backend Namespace
    required: true
    name: THOTH_BACKEND_NAMESPACE

  - description: Name of the Thoth Infra Namespace
    displayName: Thoth Infra Namespace
    required: true
    name: THOTH_INFRA_NAMESPACE

  - description: Time before analyzer pod gets removed from etcd.
    displayName: Thoth analyzer cleanup time
    required: true
    name: THOTH_ANALYZER_CLEANUP_TIME
    value: "7d"

  - description: Turn on or off automatic observation syncing to the graph database.
    displayName: Sync observations
    required: true
    name: THOTH_SYNC_OBSERVATIONS
    value: "0"

  - description: Name of bucket where results are stored to.
    displayName: Ceph bucket name
    required: true
    name: THOTH_CEPH_BUCKET
    value: "DH-DEV-DATA"

  - description: Thoth Ceph bucket prefix.
    displayName: Thoth Ceph bucket prefix
    required: true
    name: THOTH_CEPH_BUCKET_PREFIX
    value: "data/thoth"

  - description: A host:port where Ceph endpoint can be used to store/retrieve data.
    displayName: Ceph host
    required: true
    name: THOTH_S3_ENDPOINT_URL

  - description: Storage bucket name to use for persisted files
    displayName: Thoth Storage bucket name
    required: true
    value: thoth-test
    name: THOTH_DEPLOYMENT_NAME

  - displayName: THOTH_PACKAGE_RELEASES_ONLY_IF_PACKAGE_SEEN
    description: Only insert packages that have been seen within the Graph database.
    name: THOTH_PACKAGE_RELEASES_ONLY_IF_PACKAGE_SEEN
    required: true
    value: "1"

  - displayName: RSYSLOG_HOST
    description: A host to rsyslog for logging.
    name: RSYSLOG_HOST
    required: false
    value: ""

  - displayName: RSYSLOG_PORT
    description: A port to rsyslog for logging.
    name: RSYSLOG_PORT
    required: false
    value: ""

  - displayName: AMUN_API_URL
    description: An URL with scheme and path to API version of Amun service for stack validation.
    name: AMUN_API_URL
    required: false
    # e.g. http://amun-api.redhat.com/api/v1
    value: ""

  - displayName: ISIS_API_URL
    description: An url of Isis API for project2vec based queries.
    name: ISIS_API_URL
    required: false
    value: ""

  - displayName: PROMETHEUS_PUSHGATEWAY_HOST
    description: A host to push prometheus metrics via pushgateway.
    name: PROMETHEUS_PUSHGATEWAY_HOST
    required: false
    value: "pushgateway"

  - displayName: PROMETHEUS_PUSHGATEWAY_PORT
    description: A port to send prometheus metrics via pushgateway.
    name: PROMETHEUS_PUSHGATEWAY_PORT
    required: false
    value: "80"

  - displayName: SENTRY_DSN
    description: A DSN to a Sentry instance to log to.
    name: SENTRY_DSN
    required: false

  - displayName: SENTRY_ENVIRONMENT
    description: A Environment name to be used by Sentry.
    name: SENTRY_ENVIRONMENT
    required: false
